### ISSUE TITLE
Preverbs in breakdown not getting English definition

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#246] opened 2020-02-08 00:41 UTC
Following up on #244 and trying out _e-ati-pe-miyo-nitawi-nipat_:

![image](https://user-images.githubusercontent.com/15003407/74075589-697c4b00-49d0-11ea-812c-cbf6e6fc3856.png)

... it appears that preverbs with 2 characters (_ê-_ and _pê-_) or less are not indicated to have an English definition (as suggested by being underlined.

- [ ] _ê-_ should get a English definition
- [ ] _pê-_ should get an English definition.

On the other hand, ka- and kâ- are underlined.

**Comment by Madoshakalaka** [comment] 2020-02-12 18:36
just fixed it
![Screenshot from 2020-02-12 11-36-09](https://user-images.githubusercontent.com/44753941/74365765-f1c16e00-4d8b-11ea-8433-7a841fd8a88b.png)

**Comment by eddieantonio** [comment] 2020-02-12 18:40
@Madoshakalaka, the icons should be ℹ️and not (❓)! Please change this before closing this issue again.

**Comment by aarppe** [comment] 2020-02-12 19:18
Also, I'd presume that the link should take to the appropriate dictionary entry page, e.g. for _ê-_:

![image](https://user-images.githubusercontent.com/15003407/74368887-b1fd8500-4d91-11ea-9b66-e41bade814a8.png)

Right now, clicking on the preverb, you end up on the website landing page.

**Comment by Madoshakalaka** [comment] 2020-02-12 19:53
:cry: okie

**Comment by aarppe** [comment] 2020-02-12 21:42
Great!

Also, using the new crkeng.xml (we have to make sure you have access to that, which cannot be made publicly available, BTW), we'll ensure that the orthographical representations of the preverbs are correct (mostly being from CW, but some from MD as above).

**Closed** 2020-02-13 00:49 UTC
Labels: bug, sorry-matt

**Comment by Madoshakalaka** [comment] 2020-02-13 00:50
@aarppe I'll look into the new file when I'm free

**Comment by Madoshakalaka** [comment] 2020-02-13 00:56
@aarppe there's some more new issues. Could you arrange them by priority again so that I know what to focus on?

**Comment by Madoshakalaka** [comment] 2020-02-13 00:58
by the way, now the links for preverbs should go to the dictionary entry page

**Comment by aarppe** [comment] 2020-02-13 01:02
Addressing issue #255 would be good for starters, since uploading the latest version of the crk-to-eng source will resolve many issues, not just making available English translations the very latest set of lexical preverbs (as well as deduplicative elements), but also update the entire dictionary content (which will exclude non-standardized MD content, per requirement).

**Comment by Madoshakalaka** [comment] 2020-02-13 01:25
@aarppe OK

by the way, I think clicking on preverb links will still NOT bring you the correct results.
But it is caused by the bug described in #210, _i.e._ visiting directly by link does not fetch you results. I don't think it is a very urgent bug as all the search result information can be displayed by the popup.

**Comment by aarppe** [comment] 2020-02-13 01:32
@Madoshakalaka Yeah, it's not exactly what we want, but good enough for now, and addressing some other internal content issues are actually quite important right now.
