### ISSUE TITLE
Exclude parenthetical passages from phrase generation

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#704] opened 2021-03-17 22:27 UTC
In phrase generation, exclude parenthetical passages from what is sent to phrase generation. These parenthetical (and similarly excluded) passages need to be marked/coded appropriately in the dictionary source

**Comment by andrewdotn** [comment] 2021-04-20 15:07
Duplicate of #709.

**Closed by andrewdotn** 2021-04-20 15:07 UTC
Labels: Improvement
