### ISSUE TITLE
Cree word forms not getting some or all analyses

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#213] opened 2020-01-16 07:10 UTC
Pursuant #100 and #209, now the following Cree word forms are not recognized, either at all, or only receiving one of multiple possible analyses (`-`: analysis apparently missing; `+`: analysis apparently correct):

- [ ] `maskos (-maskwa+N+A+Der/Dim+N+A+Sg)`
- [ ] `maskwak (-maskwa+N+A+Pl)`
- [ ] `nimaskom (-maskwa+N+A+Px1Sg+Sg)`
- [ ] `niskak (-niska+N+A+Pl; +nîskâw+V+II+Cnj+Prs+3Sg)`
- [x] `nitas (-mitâs+N+A+D+Px1Sg+Sg; -mitâs+N+I+D+Px1Sg+Sg; -nitâs+N+A+D+Px1Sg+Sg; -nitâs+N+I+D+Px1Sg+Sg)` (two results with _nitâs_ as lemma, but `Sg` feature not showing)
- [x] `mitas (-mitâs+N+A+D+PxX+Sg; -mitâs+N+I+D+PxX+Sg)` (two results with _mitâs_ as lemma, but `Sg` feature not showing)
- [x] `mitasak (-mitâs+N+A+D+PxX+Pl)`

Dependent nouns in their lemma form are recognized, but other inflected forms such as plurals and obviatives are not.

**Comment by Madoshakalaka** [comment] 2020-01-16 22:06
looking into it

**Comment by Madoshakalaka** [comment] 2020-01-16 23:45
for the first case, it's a ridiculous error of our code misinterpreting 'maskwa+N+A+Der/Dim+N+A+Sg' as an NAD where it should be NA

**Comment by Madoshakalaka** [comment] 2020-01-17 00:34
While I just fixed the problem above, the root cause is our database couldn't resolve the lemma for `niskak` and `maskwa`, which afaik, is a bug in our implementation. I will introduce a fix.

**Comment by aarppe** [comment] 2020-03-12 01:38
@eddieantonio After some testing, it appears that the issue for _niska_, _maskwa_, and _êsa_ is a general one concerning single stem animate nouns that take the singular suffix _-a_, and mostly also _-im_. when possessed The dictionary entry forms are recognized, but none of the inflected ones result in a match (e.g.  _maskwak_, _maskos_, _nimaskom_, _nimaskos_). I'm wondering if this might have something to do with the python FST implementation, as these are the only noun forms that make use of the `@C.sg@` flag, applied for possessed forms. However, single-syllable inanimate nouns such as _wâwi_ seem to work, so that forms like _niwâwim_ are recognized.

**Comment by eddieantonio** [comment] 2020-03-12 01:43
Thanks! I'll have a look at it. The currently deployed version of the <itwewina.dev/> is not using Foma or the Python FST lookup for analysis ¯\\\_(ツ)\_/¯

**Comment by aarppe** [comment] 2020-03-12 02:28
No problem - as said, for whatever reason there are less/no issues with NIs.

**Comment by Madoshakalaka** [comment] 2020-06-09 22:36
@aarppe this should be fixed online now

**Closed** 2020-06-09 22:35 UTC
Labels: bug
