### ISSUE TITLE
Search results take too long to load

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#273] opened 2020-02-17 20:54 UTC
@Madoshakalaka has noticed this, but searching has steadily gotten too slow. Perhaps a query isn't using an index, or there is some other issue.

**Comment by aarppe** [comment] 2020-02-18 02:38
Yes, I've noticed it as well. I thought this might have potentially something to do with the revised FST, even though the changes we've implemented shouldn't have such slowing down effects. But since the revised FST hasn't been incorporated, it would seem to be a non-FST issue.

**Comment by eddieantonio** [comment] 2020-02-18 03:48
> Yes, I've noticed it as well (and am wondering where the original issue has disappeared). Anyhow, I thought this in principle could have potentially something to do with the revised FST, even though the changes we've implemented shouldn't have such slowing down effects. But since the revised FST hasn't been incorporated, it would seem to be a non-FST issue.

It's definitely not an FST issue, as it's not even used right now! We'll have to measure what happens during a query using profiling tools.

**Comment by Madoshakalaka** [comment] 2020-02-18 20:26
duplicate of #247

**Closed by Madoshakalaka** 2020-02-18 20:26 UTC
Labels: Improvement
